/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const showFailToast: typeof import('vant/es')['showFailToast']
  const showToast: typeof import('vant/es')['showToast']
}
